[package]
edition = "2021"
name = "sum-check"
version = "0.1.0"

[dependencies]
itertools = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-std = { workspace = true }
bitvec = { workspace = true }
anyhow = { workspace = true }
